/**
 * packages/db/schema/transactions.ts
 *
 * Core financial records: transactions, assignees, and tags.
 *
 * All monetary values are unsigned integer cents.
 * Transaction direction is implied by type — never by sign.
 */

import { sql } from "drizzle-orm"
import {
  boolean,
  index,
  integer,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  date,
} from "drizzle-orm/pg-core"

import { transactionTypeEnum, incomeTypeEnum } from "./enums"
import { orgs, orgMembers } from "./auth"
import { accounts } from "./accounts"
import { categories, tags } from "./classification"
import { recurringTemplates } from "./recurring"
import { importBatches } from "./imports"

/** Unsigned integer cents. */
const cents = () => integer()

/**
 * transactions
 * Central table for all financial events. Single flexible schema with
 * nullable type-specific columns. Type-specific field requirements are
 * enforced at the application layer (Zod + API), not via DB constraints.
 *
 * Money: amount is unsigned integer cents. Direction implied by type:
 *   expense / settlement / contribution → reduces account balance
 *   income / refund                     → increases account balance
 *   transfer                            → moves between accounts (net zero)
 *
 * Type-specific nullable column usage:
 *   account_id           → expense, refund, income, settlement, contribution
 *   category_id          → expense, refund
 *   from_account_id      → transfer
 *   to_account_id        → transfer
 *   settled_account_id   → settlement (the shared account being settled)
 *   refund_of_id         → refund (optional link to original transaction)
 *   recurring_template_id → any type (when generated by a template)
 *   import_batch_id      → any type (when created via CSV import)
 *   income_type          → income
 *   income_source        → income
 */
export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => orgs.id, { onDelete: "cascade" }),
    type: transactionTypeEnum("type").notNull(),
    date: date("date").notNull(),
    /** Unsigned integer cents. Direction implied by type — never signed. */
    amount: cents().notNull(),
    description: text("description").notNull(),
    /**
     * Original raw value from CSV import.
     * Preserved for display alongside the edited description.
     * Null for manually entered transactions.
     */
    rawDescription: text("raw_description"),

    // --- Type-specific FKs ---
    /** Used by: expense, refund, income, settlement, contribution */
    accountId: uuid("account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    /** Used by: expense, refund */
    categoryId: uuid("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    /** Used by: transfer */
    fromAccountId: uuid("from_account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    /** Used by: transfer */
    toAccountId: uuid("to_account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    /**
     * Used by: settlement
     * The shared account whose balance this payment reduces.
     * Enables deduplication when the same settlement appears in two CSV
     * exports (e.g. outgoing e-transfer on payer's statement AND incoming
     * payment on the account being settled).
     */
    settledAccountId: uuid("settled_account_id").references(() => accounts.id, {
      onDelete: "set null",
    }),
    /**
     * Used by: refund
     * Optional link to the original expense being reversed.
     * If present, the original transaction's split is pre-filled as the
     * default split for this refund. Self-referential FK.
     */
    refundOfId: uuid("refund_of_id").references(
      (): ReturnType<typeof uuid> => transactions.id,
      { onDelete: "set null" }
    ),
    /**
     * Present when this transaction was generated by a recurring template.
     * Null for manually created and imported transactions.
     */
    recurringTemplateId: uuid("recurring_template_id").references(
      () => recurringTemplates.id,
      { onDelete: "set null" }
    ),
    /**
     * Present when this transaction was created via CSV import.
     * Null for manually created transactions.
     */
    importBatchId: uuid("import_batch_id").references(
      () => importBatches.id,
      { onDelete: "set null" }
    ),

    // --- Income-specific fields (null for all other types) ---
    incomeType: incomeTypeEnum("income_type"),
    /** Freeform string — who the money came from (e.g. "Employer", "Client"). */
    incomeSource: text("income_source"),

    // --- Optional fields ---
    notes: text("notes"),
    /**
     * Bank-assigned transaction reference ID from CSV export.
     * Primary duplicate detection signal when present.
     * Surfaced only via transaction context menu — not shown by default.
     */
    externalId: text("external_id"),
    /**
     * True when a user has identified this as a duplicate.
     * Excluded from all calculations but preserved in the DB (not deleted).
     */
    isDuplicate: boolean("is_duplicate").notNull().default(false),

    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index("transactions_org_idx").on(t.orgId),
    index("transactions_org_date_idx").on(t.orgId, t.date),
    index("transactions_org_type_idx").on(t.orgId, t.type),
    index("transactions_account_idx").on(t.accountId),
    index("transactions_category_idx").on(t.categoryId),
    index("transactions_import_batch_idx").on(t.importBatchId),
    index("transactions_recurring_template_idx").on(t.recurringTemplateId),
  ]
)

/**
 * transaction_assignees
 * Which org members own a share of a transaction, and how much.
 *
 * Both amount (cents) and percentage are stored for display flexibility.
 * percentage is numeric(5,2) — the sole exception to the integer-cents rule,
 * since it is a ratio (e.g. 33.33), not a monetary value.
 *
 * Invariants enforced in application layer:
 *   - Sum of all amounts for a transaction = transaction.amount
 *   - Sum of all percentages for a transaction = 100.00
 *   - Adding/removing an assignee resets to an even split
 */
export const transactionAssignees = pgTable(
  "transaction_assignees",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    memberId: uuid("member_id")
      .notNull()
      .references(() => orgMembers.id, { onDelete: "cascade" }),
    /** This assignee's share in unsigned integer cents. */
    amount: cents().notNull(),
    /**
     * This assignee's share as a percentage.
     * numeric(5,2) allows values like 33.33, 50.00, 100.00.
     * Sum across all assignees on a transaction must equal 100.00.
     */
    percentage: numeric("percentage", { precision: 5, scale: 2 }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    uniqueIndex("transaction_assignees_txn_member_idx").on(
      t.transactionId,
      t.memberId
    ),
    index("transaction_assignees_txn_idx").on(t.transactionId),
    index("transaction_assignees_member_idx").on(t.memberId),
  ]
)

/**
 * transaction_tags
 * Many-to-many join between transactions and tags.
 */
export const transactionTags = pgTable(
  "transaction_tags",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    transactionId: uuid("transaction_id")
      .notNull()
      .references(() => transactions.id, { onDelete: "cascade" }),
    tagId: uuid("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
  },
  (t) => [
    uniqueIndex("transaction_tags_txn_tag_idx").on(t.transactionId, t.tagId),
    index("transaction_tags_txn_idx").on(t.transactionId),
  ]
)
