/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutAccountsRouteImport } from './routes/_layout.accounts'
import { Route as LayoutTransactionsRouteRouteImport } from './routes/_layout.transactions/route'
import { Route as LayoutSettingsRouteRouteImport } from './routes/_layout.settings/route'
import { Route as LayoutTransactionsIndexRouteImport } from './routes/_layout.transactions/index'
import { Route as LayoutSettingsMerchantRulesRouteImport } from './routes/_layout.settings/merchant-rules'
import { Route as LayoutSettingsHouseholdRouteImport } from './routes/_layout.settings/household'
import { Route as LayoutSettingsCategoriesRouteImport } from './routes/_layout.settings/categories'
import { Route as LayoutTransactionsImportRouteRouteImport } from './routes/_layout.transactions/import/route'
import { Route as LayoutTransactionsImportIndexRouteImport } from './routes/_layout.transactions/import/index'
import { Route as LayoutTransactionsImportHistoryRouteImport } from './routes/_layout.transactions/import/history'
import { Route as LayoutTransactionsImportDraftIdRouteRouteImport } from './routes/_layout.transactions/import/$draftId/route'
import { Route as LayoutTransactionsImportDraftIdIndexRouteImport } from './routes/_layout.transactions/import/$draftId/index'
import { Route as LayoutTransactionsImportDraftIdFinalizeRouteImport } from './routes/_layout.transactions/import/$draftId/finalize'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountsRoute = LayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransactionsRouteRoute = LayoutTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRouteRoute = LayoutSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransactionsIndexRoute = LayoutTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTransactionsRouteRoute,
} as any)
const LayoutSettingsMerchantRulesRoute =
  LayoutSettingsMerchantRulesRouteImport.update({
    id: '/merchant-rules',
    path: '/merchant-rules',
    getParentRoute: () => LayoutSettingsRouteRoute,
  } as any)
const LayoutSettingsHouseholdRoute = LayoutSettingsHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => LayoutSettingsRouteRoute,
} as any)
const LayoutSettingsCategoriesRoute =
  LayoutSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => LayoutSettingsRouteRoute,
  } as any)
const LayoutTransactionsImportRouteRoute =
  LayoutTransactionsImportRouteRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => LayoutTransactionsRouteRoute,
  } as any)
const LayoutTransactionsImportIndexRoute =
  LayoutTransactionsImportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutTransactionsImportRouteRoute,
  } as any)
const LayoutTransactionsImportDraftIdRouteRoute =
  LayoutTransactionsImportDraftIdRouteRouteImport.update({
    id: '/$draftId',
    path: '/$draftId',
    getParentRoute: () => LayoutTransactionsImportRouteRoute,
  } as any)
const LayoutTransactionsImportHistoryRoute =
  LayoutTransactionsImportHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => LayoutTransactionsImportRouteRoute,
  } as any)
const LayoutTransactionsImportDraftIdIndexRoute =
  LayoutTransactionsImportDraftIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutTransactionsImportDraftIdRouteRoute,
  } as any)
const LayoutTransactionsImportDraftIdFinalizeRoute =
  LayoutTransactionsImportDraftIdFinalizeRouteImport.update({
    id: '/finalize',
    path: '/finalize',
    getParentRoute: () => LayoutTransactionsImportDraftIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof LayoutSettingsRouteRouteWithChildren
  '/transactions': typeof LayoutTransactionsRouteRouteWithChildren
  '/accounts': typeof LayoutAccountsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/transactions/import': typeof LayoutTransactionsImportRouteRouteWithChildren
  '/settings/categories': typeof LayoutSettingsCategoriesRoute
  '/settings/household': typeof LayoutSettingsHouseholdRoute
  '/settings/merchant-rules': typeof LayoutSettingsMerchantRulesRoute
  '/transactions/': typeof LayoutTransactionsIndexRoute
  '/transactions/import/$draftId': typeof LayoutTransactionsImportDraftIdRouteRouteWithChildren
  '/transactions/import/': typeof LayoutTransactionsImportIndexRoute
  '/transactions/import/history': typeof LayoutTransactionsImportHistoryRoute
  '/transactions/import/$draftId/': typeof LayoutTransactionsImportDraftIdIndexRoute
  '/transactions/import/$draftId/finalize': typeof LayoutTransactionsImportDraftIdFinalizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof LayoutSettingsRouteRouteWithChildren
  '/accounts': typeof LayoutAccountsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/settings/categories': typeof LayoutSettingsCategoriesRoute
  '/settings/household': typeof LayoutSettingsHouseholdRoute
  '/settings/merchant-rules': typeof LayoutSettingsMerchantRulesRoute
  '/transactions': typeof LayoutTransactionsIndexRoute
  '/transactions/import/$draftId': typeof LayoutTransactionsImportDraftIdIndexRoute
  '/transactions/import': typeof LayoutTransactionsImportIndexRoute
  '/transactions/import/history': typeof LayoutTransactionsImportHistoryRoute
  '/transactions/import/$draftId/finalize': typeof LayoutTransactionsImportDraftIdFinalizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_layout/settings': typeof LayoutSettingsRouteRouteWithChildren
  '/_layout/transactions': typeof LayoutTransactionsRouteRouteWithChildren
  '/_layout/accounts': typeof LayoutAccountsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_layout/transactions/import': typeof LayoutTransactionsImportRouteRouteWithChildren
  '/_layout/settings/categories': typeof LayoutSettingsCategoriesRoute
  '/_layout/settings/household': typeof LayoutSettingsHouseholdRoute
  '/_layout/settings/merchant-rules': typeof LayoutSettingsMerchantRulesRoute
  '/_layout/transactions/': typeof LayoutTransactionsIndexRoute
  '/_layout/transactions/import/$draftId': typeof LayoutTransactionsImportDraftIdRouteRouteWithChildren
  '/_layout/transactions/import/': typeof LayoutTransactionsImportIndexRoute
  '/_layout/transactions/import/history': typeof LayoutTransactionsImportHistoryRoute
  '/_layout/transactions/import/$draftId/': typeof LayoutTransactionsImportDraftIdIndexRoute
  '/_layout/transactions/import/$draftId/finalize': typeof LayoutTransactionsImportDraftIdFinalizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/transactions'
    | '/accounts'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/transactions/import'
    | '/settings/categories'
    | '/settings/household'
    | '/settings/merchant-rules'
    | '/transactions/'
    | '/transactions/import/$draftId'
    | '/transactions/import/'
    | '/transactions/import/history'
    | '/transactions/import/$draftId/'
    | '/transactions/import/$draftId/finalize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/accounts'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/settings/categories'
    | '/settings/household'
    | '/settings/merchant-rules'
    | '/transactions'
    | '/transactions/import/$draftId'
    | '/transactions/import'
    | '/transactions/import/history'
    | '/transactions/import/$draftId/finalize'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/onboarding'
    | '/_layout/settings'
    | '/_layout/transactions'
    | '/_layout/accounts'
    | '/_layout/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_layout/transactions/import'
    | '/_layout/settings/categories'
    | '/_layout/settings/household'
    | '/_layout/settings/merchant-rules'
    | '/_layout/transactions/'
    | '/_layout/transactions/import/$draftId'
    | '/_layout/transactions/import/'
    | '/_layout/transactions/import/history'
    | '/_layout/transactions/import/$draftId/'
    | '/_layout/transactions/import/$draftId/finalize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accounts': {
      id: '/_layout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transactions': {
      id: '/_layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof LayoutTransactionsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transactions/': {
      id: '/_layout/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof LayoutTransactionsIndexRouteImport
      parentRoute: typeof LayoutTransactionsRouteRoute
    }
    '/_layout/settings/merchant-rules': {
      id: '/_layout/settings/merchant-rules'
      path: '/merchant-rules'
      fullPath: '/settings/merchant-rules'
      preLoaderRoute: typeof LayoutSettingsMerchantRulesRouteImport
      parentRoute: typeof LayoutSettingsRouteRoute
    }
    '/_layout/settings/household': {
      id: '/_layout/settings/household'
      path: '/household'
      fullPath: '/settings/household'
      preLoaderRoute: typeof LayoutSettingsHouseholdRouteImport
      parentRoute: typeof LayoutSettingsRouteRoute
    }
    '/_layout/settings/categories': {
      id: '/_layout/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof LayoutSettingsCategoriesRouteImport
      parentRoute: typeof LayoutSettingsRouteRoute
    }
    '/_layout/transactions/import': {
      id: '/_layout/transactions/import'
      path: '/import'
      fullPath: '/transactions/import'
      preLoaderRoute: typeof LayoutTransactionsImportRouteRouteImport
      parentRoute: typeof LayoutTransactionsRouteRoute
    }
    '/_layout/transactions/import/': {
      id: '/_layout/transactions/import/'
      path: '/'
      fullPath: '/transactions/import/'
      preLoaderRoute: typeof LayoutTransactionsImportIndexRouteImport
      parentRoute: typeof LayoutTransactionsImportRouteRoute
    }
    '/_layout/transactions/import/$draftId': {
      id: '/_layout/transactions/import/$draftId'
      path: '/$draftId'
      fullPath: '/transactions/import/$draftId'
      preLoaderRoute: typeof LayoutTransactionsImportDraftIdRouteRouteImport
      parentRoute: typeof LayoutTransactionsImportRouteRoute
    }
    '/_layout/transactions/import/history': {
      id: '/_layout/transactions/import/history'
      path: '/history'
      fullPath: '/transactions/import/history'
      preLoaderRoute: typeof LayoutTransactionsImportHistoryRouteImport
      parentRoute: typeof LayoutTransactionsImportRouteRoute
    }
    '/_layout/transactions/import/$draftId/': {
      id: '/_layout/transactions/import/$draftId/'
      path: '/'
      fullPath: '/transactions/import/$draftId/'
      preLoaderRoute: typeof LayoutTransactionsImportDraftIdIndexRouteImport
      parentRoute: typeof LayoutTransactionsImportDraftIdRouteRoute
    }
    '/_layout/transactions/import/$draftId/finalize': {
      id: '/_layout/transactions/import/$draftId/finalize'
      path: '/finalize'
      fullPath: '/transactions/import/$draftId/finalize'
      preLoaderRoute: typeof LayoutTransactionsImportDraftIdFinalizeRouteImport
      parentRoute: typeof LayoutTransactionsImportDraftIdRouteRoute
    }
  }
}

interface LayoutSettingsRouteRouteChildren {
  LayoutSettingsCategoriesRoute: typeof LayoutSettingsCategoriesRoute
  LayoutSettingsHouseholdRoute: typeof LayoutSettingsHouseholdRoute
  LayoutSettingsMerchantRulesRoute: typeof LayoutSettingsMerchantRulesRoute
}

const LayoutSettingsRouteRouteChildren: LayoutSettingsRouteRouteChildren = {
  LayoutSettingsCategoriesRoute: LayoutSettingsCategoriesRoute,
  LayoutSettingsHouseholdRoute: LayoutSettingsHouseholdRoute,
  LayoutSettingsMerchantRulesRoute: LayoutSettingsMerchantRulesRoute,
}

const LayoutSettingsRouteRouteWithChildren =
  LayoutSettingsRouteRoute._addFileChildren(LayoutSettingsRouteRouteChildren)

interface LayoutTransactionsImportDraftIdRouteRouteChildren {
  LayoutTransactionsImportDraftIdIndexRoute: typeof LayoutTransactionsImportDraftIdIndexRoute
  LayoutTransactionsImportDraftIdFinalizeRoute: typeof LayoutTransactionsImportDraftIdFinalizeRoute
}

const LayoutTransactionsImportDraftIdRouteRouteChildren: LayoutTransactionsImportDraftIdRouteRouteChildren =
  {
    LayoutTransactionsImportDraftIdIndexRoute:
      LayoutTransactionsImportDraftIdIndexRoute,
    LayoutTransactionsImportDraftIdFinalizeRoute:
      LayoutTransactionsImportDraftIdFinalizeRoute,
  }

const LayoutTransactionsImportDraftIdRouteRouteWithChildren =
  LayoutTransactionsImportDraftIdRouteRoute._addFileChildren(
    LayoutTransactionsImportDraftIdRouteRouteChildren,
  )

interface LayoutTransactionsImportRouteRouteChildren {
  LayoutTransactionsImportDraftIdRouteRoute: typeof LayoutTransactionsImportDraftIdRouteRouteWithChildren
  LayoutTransactionsImportHistoryRoute: typeof LayoutTransactionsImportHistoryRoute
  LayoutTransactionsImportIndexRoute: typeof LayoutTransactionsImportIndexRoute
}

const LayoutTransactionsImportRouteRouteChildren: LayoutTransactionsImportRouteRouteChildren =
  {
    LayoutTransactionsImportDraftIdRouteRoute:
      LayoutTransactionsImportDraftIdRouteRouteWithChildren,
    LayoutTransactionsImportHistoryRoute: LayoutTransactionsImportHistoryRoute,
    LayoutTransactionsImportIndexRoute: LayoutTransactionsImportIndexRoute,
  }

const LayoutTransactionsImportRouteRouteWithChildren =
  LayoutTransactionsImportRouteRoute._addFileChildren(
    LayoutTransactionsImportRouteRouteChildren,
  )

interface LayoutTransactionsRouteRouteChildren {
  LayoutTransactionsImportRouteRoute: typeof LayoutTransactionsImportRouteRouteWithChildren
  LayoutTransactionsIndexRoute: typeof LayoutTransactionsIndexRoute
}

const LayoutTransactionsRouteRouteChildren: LayoutTransactionsRouteRouteChildren =
  {
    LayoutTransactionsImportRouteRoute:
      LayoutTransactionsImportRouteRouteWithChildren,
    LayoutTransactionsIndexRoute: LayoutTransactionsIndexRoute,
  }

const LayoutTransactionsRouteRouteWithChildren =
  LayoutTransactionsRouteRoute._addFileChildren(
    LayoutTransactionsRouteRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutSettingsRouteRoute: typeof LayoutSettingsRouteRouteWithChildren
  LayoutTransactionsRouteRoute: typeof LayoutTransactionsRouteRouteWithChildren
  LayoutAccountsRoute: typeof LayoutAccountsRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRouteRoute: LayoutSettingsRouteRouteWithChildren,
  LayoutTransactionsRouteRoute: LayoutTransactionsRouteRouteWithChildren,
  LayoutAccountsRoute: LayoutAccountsRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
